config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :posts
  root :to => "posts#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many  :posts
    validates :name, :presence=>true
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :create_service
    before_action :set_category, only: [:edit, :update, :destroy]


	def index
		@categories = @category_service.all
	end

    def edit
    end

    def update
       category_save
    end

    def new
       @category = @category_service.new
    end

    def create
       @category = @category_service.new
       category_save
    end

    def destroy
       @category.destroy
       respond_to do |format|
          format.html { redirect_to categories_path, notice: 'La categoría fue eliminado correctamente.' }
          format.json { head :no_content }
       end
    end

    private

    def category_save
      category_assign_fields

        respond_to do |format|
          if @category.save
            format.html { redirect_to categories_path, notice: 'Registro Guardado Satisfactoriamente' }
            format.json { render :index, status: :created, location: @category }
          else
            format.html { render :new }
            format.json { render json: @category.errors, status: :unprocessable_entity }
          end
        end

    end

    def category_assign_fields
        @category.name = params[:category][:name]
    end

    def set_category
        @category = @category_service.find params[:id]

    rescue ActiveRecord::RecordNotFound
        flash[:error] = "La categoría no existe"
        redirect_to categories_path
    end

    def create_service
      @category_service = CategoryService.new
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :create_service
    before_action :set_post, only: [:edit, :update, :destroy, :show]

    def index
        @posts = @post_service.all
    end

    def show
    end

    def new
        @post = @post_service.new
    end

    def create
        @post = @post_service.new
        @post.publish_date = Time.now.to_i
        post_save
    end

    private

    def post_save
      post_assign_fields

        respond_to do |format|
          if @post.save
            format.html { redirect_to posts_path, notice: 'Registro Guardado Satisfactoriamente' }
            format.json { render :index, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end

    end

    def post_assign_fields
        @post.title       = params[:post][:title]
        @post.body        = params[:post][:body]
        @post.category_id = params[:post][:category_id]
    end

    def set_post
        @post = @post_service.find params[:id]

    rescue ActiveRecord::RecordNotFound
        flash[:error] = "El post no existe"
        redirect_to posts_path
    end

    def create_service
      @post_service = PostService.new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<%= render 'shared/error_messages', object: @category %>
  <div class="form-group">
    <%= f.label :name, 'Nombre:' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= "Editando "+ @category.name %></h1>
  </div>

  <%= render 'shared/flash_messages'%>

  <div class="panel-body">
    <p>
      <%= link_to "Regresar al listado", :action => "index" %>
    </p>
  </div>

  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Listado de Categorías</h1>
  </div>

    <%= render 'shared/flash_messages'%>
    <div>
      <%= link_to 'Agregar Categoría', new_category_path, class: 'btn btn-success' %>
    </div>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td>
            <%= category.name %>
          </td>
          <td class="item">
            <%= link_to 'Editar',  edit_category_path(category), :id =>"ed"+category.id.to_s %>
            <%= link_to 'Eliminar', category, method: :delete, :id => "del" + category.id.to_s %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Agregar una categoría</h1>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to "Regresar al listado", :action => "index" %>
    </p>
  </div>

  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">


</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<%= render 'shared/error_messages', object: @post %>
  <div class="form-group">
    <%= f.label :title, 'Nombre:' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body, 'body:' %>
    <%= f.text_field :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id, 'Categoría:' %>
    <%= f.collection_select(:category_id, Category.all, :id, :name ) %>
  </div>

  <div class="form-group">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container bs-docs-container">
  <%= render 'shared/flash_messages'%>

  <div>
    <%= link_to 'Agregar Post', new_post_path, class: 'btn btn-success' %>
  </div>


  <% @posts.each do |post| %>
    <div class="row">
      <div class = "bs-docs-section">
        <div class="bs-callout bs-callout-info" id="callout-xref-input-group">
          <h4 id="input-groups"><%= post.title  %><a class="anchorjs-link" href="#input-groups">
            <span class="anchorjs-icon"></span></a>
          </h4>
          <div id="datos del post">
             <h5>
               <% if !post.publish_date.nil? %>
                  <span><%= Time.at(post.publish_date) %></span>
               <% end if %>
               <span><%= post.category.name %></span>
             </h5>
          </div>

            <p>
              <%= post.body %>
              <%= link_to 'Ver post',  post_path(post), :id =>"pos"+post.id.to_s %>
            </p>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Agregar Post</h1><hr>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to "Regresar al listado", :action => "index" %>
    </p>
  </div>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"><%= @post.title %></h1>
  </div>

    <%= render 'shared/flash_messages'%>
    <div>
      <%= @post.body %>
    </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">Comentarios</h1>
  </div>

  <div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
  <% flash.each do |key, value| %>
    <div class="flash alert alert-<%= key %>">
    <%= value %>
    </div>
    <% end %>
  <%= yield %>